# Dependencies
markdown:            kramdown
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Ninety-Plus of Blue
tagline:             "an aesthete's guide to shouting in public"
description:         "Call it an aesthete's football journal; call it a grad student's distraction. Call it a passionate defense of Adam Nemec (leave Nemec alone!). I call it bullshit."
url:                 http://prpole.github.io/ninety-plus-of-blue/
#baseurl:             ninety-plus-of-blue
paginate:            5

# About/contact
author:
  name:              Phillip R. Polefrone
  url:               https://twitter.com/polefrone
  email:             prmpolefrone@gmail.com

# Custom vars
version:             1.0.0
